grafana:
    image: monitoringartist/grafana-xxl
    ports:
        - "3000:3000"
    links:
        - influxdb
influxdb:
    image: tutum/influxdb
    ports:
        - "8083:8083"
        - "8086:8086"
